config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'pages#home'
  root 'pages#home'
  
  get 'pages/about'
  get 'about' => 'pages#about'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def home
    
  end
  
  def about
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Dylan Zitzmann</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>

  <body>

    <!-- Static navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Developer</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class=""><%= link_to "Home", home_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><a href="/home#works">Works</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

		<%= yield %>
    <%= debug(params) if Rails.env.development? %>

	<div id="footerwrap">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-4">
					<p><b>WEB DEVELOPER</b></p>
				</div>
			
				<div class="col-lg-4">
					<p>Living in the beautiful Tampa Bay area.</p>
				</div>
				<div class="col-lg-4">
					<p>dtzitz@live.com</p>
				</div>
			</div>
		</div>
	</div><! --/footerwrap -->
	


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div id="aboutwrap">
	    <div class="container">
			<div class="row">
				<div class="col-lg-6 col-lg-offset-3">
				</div>
			</div><! --/row -->
	    </div> <!-- /container -->
	</div><! --/aboutwrap -->
	
	<div class="container">
		<div class="row centered mt mb">
			<div class="col-lg-8 col-lg-offset-2">
				<h2>DYLAN ZITZMANN</h2>
				<p>I am currently pursuing my Bachelors degree in technology management and looking for projects to add to my portfolio.</p>
			</div>

		</div><! --/row -->
</div><! --/container -->

app/views/pages/home.html.erb
	<div id="headerwrap">
	    <div class="container">
			<div class="row">
				<div class="col-lg-6 col-lg-offset-3">
					<h4>HELLO, MY NAME IS</h4>
					<h1>Dylan Zitzmann</h1>
					<h4>DEVELOPER</h4>
				</div>
			</div><! --/row -->
	    </div> <!-- /container -->
	</div><! --/headerwrap -->
	
	<section id="works"></section>
	<div class="container">
		<div class="row centered mt mb">
			<h1>My Portfolio</h1>
			
			<div class="col-lg-6 col-lg-offset-3">  <h1> <a href="http://depot.meteor.com"> <i class="fa fa-truck"></i> <br> Meteor Depot</a> </h1> </div>
			
		</div><! --/row -->
		<div class="row centered mt mb">
			<div class="col-lg-6 col-lg-offset-3"><a href="https://bitbucket.org/dtzitz/"><%= image_tag("bitbucket.png") %></a></div>
		</div>
	</div><! --/container -->
	
	<div id="social">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-4">
					 <h2> <a href="http://www.twitter.com/dtzitz"><i class="fa fa-twitter"></i></a> </h2>
				</div>
				<div class="col-lg-4">
					<a href="http://www.linkedin.com/in/dylanz"><i class="fa fa-linkedin"></i></a>
				</div>
				<div class="col-lg-4">
					<a href="http://dtzitz.tumblr.com/"><i class="fa fa-tumblr"></i></a>
				</div>
			
			</div><! --/row -->
		</div><! --/container -->
	</div><! --/social -->